version: "3.9"

services:

  backend:
    build: ./m-motors-back
    container_name: m-motors-back
    ports:
      - "5000:5000"
    env_file:
      - ./m-motors-back/.env
    restart: always

  frontend:
    build: ./m-motors-front
    container_name: m-motors-front
    ports:
      - "80:80"
    restart: always
