"""add document fields

Revision ID: 361febeeeafb
Revises: 8d3e8372b20b
Create Date: 2026-06-10 10:32:17.443031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361febeeeafb'
down_revision: Union[str, Sequence[str], None] = '8d3e8372b20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('type_document', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'type_document')
    # ### end Alembic commands ###
