"""update vehicles model

Revision ID: 8d3e8372b20b
Revises: 3eb8cee2dadb
Create Date: 2026-06-07 12:39:05.102836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3e8372b20b'
down_revision: Union[str, Sequence[str], None] = '3eb8cee2dadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=20), nullable=False))
    op.add_column('vehicles', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('vehicles', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'is_deleted')
    op.drop_column('vehicles', 'category')
    op.drop_column('vehicles', 'vehicle_type')
    # ### end Alembic commands ###
